### ISSUE TITLE
Tagme and Entity recognition

### ISSUE THREAD

**Issue by 2213500360** [PhilippChr/CONVEX#12]
Hello, I want know what is the proportion of errors caused by tagme's inability to recognize entities in your work? Because I tried to use tagme to identify the first question of many conversations in the test set, and found that some entity were unrecognizable. For example, the first question in test set, "what is the name of the writer of the secret garden?", The entity expected to be recognized is "the secret garden", but tagme can only recognize "secret garden",the former is book, the latter is not.

In addition, in the dialogue with conv_id 8974 in the test set, its first problem is the referential pronoun "he", which obviously can not identify the entity. Is this a data set error?

**Comment by PhilippChr** [comment]
Hello,

I do not have a concrete number for the proportion of NERD errors,
but we measured an answer presence (in the 1-hop of disambiguated entities)
of roughly 70-80% in the first turn.

The remaining 20-30 % can be errors due to NERD (as you pointed out),
incomplete KG (structure or content) or also noise in the dataset.

There can also be rare cases in which the initial question is incomplete,
however we tried to identify such semi-automatically using NER and tagging
questions without entity mentions. But for conv_id 8974, this is indeed a 
dataset error (I think TagMe labels 'first team' as entity, which is why it was
not detected).

Regards,
Philipp
