### ISSUE TITLE
Different knowledge bases

### ISSUE THREAD

**Issue by RomainClaret** [PhilippChr/CONVEX#2]
Hi,

I played a bit with your benchmark. I am finding the exact same individual results across all domain options, even with a different number of frontiers and particularly with different knowledge bases from [http://www.rdfhdt.org/datasets/](http://www.rdfhdt.org/datasets/).

I tried with python27 and python37.

Additionally, I am not finding the same results as in your paper :-(

Thank you for your time,
Best regards

**Comment by PhilippChr** [comment]
Hi,

* The model caches the neighborhood from the KG for occuring entities. So if you exchange the KG, you should delete this cache as well. But this method is also designed to work on wikidata.

* The results on the paper differ, because we provide a new train-valid-test split. In the paper, we had a small dev-set (20%) and a larger test-set(80%). If you want to reproduce our results from the paper, I can send you the corresponding benchmark split after the conference.

* You need to specify the domain in the settings. The domain name should be specified (in the settings.json) by either 'books', 'movies', 'music', tv_series' or 'soccer'.
You can also set the domain to 'ALL' and exchange the path to the test-set (e.g. '../test_set_books.json') in the settings file.

Regards,
Philipp
